// <auto-generated />
namespace CalCount.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class bootz : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bootz));
        
        string IMigrationMetadata.Id
        {
            get { return "201403140214571_bootz"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
